<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title'             => '7 Thói Quen Của Bạn Trẻ Thành Đạt',
                'slug'              => '7-thoi-quen-cua-ban-tre-thanh-dat',
                'author'            => 'Sean Covery',
                'publisher'         => 'NXB Tổng Hợp',
                'price'             => 99000,
                'original_price'    => 120000,
                'description'       => 'Sách phát triển bản thân dành cho giới trẻ, giúp bạn hình thành thói quen thành công từ sớm.',
                'short_description' => 'Hình thành thói quen thành công từ sớm.',
                'stock'             => 23,
                'category_id'       => 2, // Phát triển bản thân
                'image'             => '7-thoi-quen-cua-ban-tre-thanh-dat.jpg',
                'pages'             => 350,
                'language'          => 'Tiếng Việt',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Alice In Borderland - Tập 1',
                'slug'              => 'alice-in-borderland-tap-1',
                'author'            => 'Haro Aso',
                'publisher'         => 'NXB Trẻ',
                'price'             => 120000,
                'description'       => 'Truyện tranh hành động gay cấn, lấy bối cảnh thế giới sinh tồn đầy kịch tính.',
                'short_description' => 'Truyện tranh sinh tồn đầy kịch tính.',
                'stock'             => 16,
                'category_id'       => 4, // Thiếu nhi
                'image'             => 'alice-in-borderland-tap-1.jpg',
                'pages'             => 200,
                'language'          => 'Tiếng Việt',
            ],
            [
                'title'             => 'Bố Già',
                'slug'              => 'bo-gia-mario-puzo',
                'author'            => 'Mario Puzo',
                'publisher'         => 'NXB Văn Học',
                'price'             => 150000,
                'original_price'    => 185000,
                'description'       => 'Tiểu thuyết kinh điển về thế giới mafia Ý tại Mỹ, tác phẩm bất hủ của nền văn học thế giới.',
                'short_description' => 'Tiểu thuyết kinh điển về thế giới mafia.',
                'stock'             => 10,
                'category_id'       => 1, // Văn Học
                'image'             => 'bo-gia-mario-puzo.jpg',
                'pages'             => 448,
                'language'          => 'Tiếng Việt',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Đi Tìm Lẽ Sống',
                'slug'              => 'di-tim-le-song',
                'author'            => 'Viktor E. Frankl',
                'publisher'         => 'NXB Tri Thức',
                'price'             => 140000,
                'original_price'    => 160000,
                'description'       => 'Câu chuyện về ý nghĩa cuộc sống từ trải nghiệm trong trại tập trung, truyền cảm hứng sống tích cực.',
                'short_description' => 'Tìm ý nghĩa cuộc sống qua nghịch cảnh.',
                'stock'             => 20,
                'category_id'       => 2,
                'image'             => 'di-tim-le-song.jpg',
                'pages'             => 239,
                'language'          => 'Tiếng Việt',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Đồng Tháp Đất & Người Tập 10',
                'slug'              => 'dong-thap-dat-va-nguoi-tap-10',
                'author'            => 'Nhiều tác giả',
                'publisher'         => 'NXB Đồng Nai',
                'price'             => 80000,
                'description'       => 'Tuyển tập văn học về vùng đất và con người Đồng Tháp.',
                'short_description' => 'Văn học về vùng đất Đồng Tháp.',
                'stock'             => 10,
                'category_id'       => 1,
                'image'             => 'dong-thap-dat-va-nguoi-tap-10.jpg',
                'pages'             => 180,
                'language'          => 'Tiếng Việt',
            ],
            [
                'title'             => 'Doraemon - Túi Thần Kỳ Của Doraemon',
                'slug'              => 'doraemon-tui-than-ky-cua-doraemon',
                'author'            => 'Fujiko F. Fujio',
                'publisher'         => 'NXB Kim Đồng',
                'price'             => 60000,
                'description'       => 'Truyện tranh thiếu nhi kinh điển về chú mèo máy Doraemon và những bảo bối thần kỳ.',
                'short_description' => 'Chú mèo máy và những bảo bối thần kỳ.',
                'stock'             => 37,
                'category_id'       => 4,
                'image'             => 'doraemon-tui-than-ky-cua-doraemon.jpg',
                'pages'             => 192,
                'language'          => 'Tiếng Việt',
            ],
            [
                'title'             => 'Harry Potter và Hòn Đá Phù Thủy',
                'slug'              => 'harry-potter-va-hon-da-phu-thuy',
                'author'            => 'J.K. Rowling',
                'publisher'         => 'NXB Trẻ',
                'price'             => 170000,
                'original_price'    => 200000,
                'description'       => 'Cuốn sách đầu tiên trong series Harry Potter, mở ra thế giới phép thuật huyền bí và kỳ diệu.',
                'short_description' => 'Khởi đầu thế giới phép thuật Harry Potter.',
                'stock'             => 22,
                'category_id'       => 1,
                'image'             => 'harry-potter-va-hon-da-phu-thuy.jpg',
                'pages'             => 366,
                'language'          => 'Tiếng Việt',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Không Gì Là Không Thể',
                'slug'              => 'khong-gi-la-khong-the',
                'author'            => 'George Matthew Adams',
                'publisher'         => 'NXB Tổng Hợp Tp.HCM',
                'price'             => 85000,
                'description'       => 'Sách truyền động lực, khơi dậy niềm tin rằng không có giới hạn nào cho sự cố gắng.',
                'short_description' => 'Khơi dậy niềm tin và động lực sống.',
                'stock'             => 30,
                'category_id'       => 2,
                'image'             => 'khong-gi-la-khong-the.jpg',
                'pages'             => 272,
                'language'          => 'Tiếng Việt',
            ],
            [
                'title'             => 'Marketing Căn Bản',
                'slug'              => 'marketing-can-ban',
                'author'            => 'Don Sexton',
                'publisher'         => 'NXB Lao Động',
                'price'             => 110000,
                'description'       => 'Nền tảng marketing cơ bản cho người mới bắt đầu, từ khái niệm đến chiến lược thực tế.',
                'short_description' => 'Nền tảng marketing cho người mới.',
                'stock'             => 15,
                'category_id'       => 3,
                'image'             => 'marketing-can-ban.jpg',
                'pages'             => 320,
                'language'          => 'Tiếng Việt',
            ],
            [
                'title'             => 'Nhà Giả Kim',
                'slug'              => 'nha-gia-kim',
                'author'            => 'Paulo Coelho',
                'publisher'         => 'NXB Văn Học',
                'price'             => 130000,
                'original_price'    => 155000,
                'description'       => 'Tiểu thuyết nổi tiếng thế giới về hành trình theo đuổi giấc mơ và lắng nghe tiếng gọi trái tim.',
                'short_description' => 'Hành trình theo đuổi giấc mơ.',
                'stock'             => 28,
                'category_id'       => 1,
                'image'             => 'nha-gia-kim.jpg',
                'pages'             => 228,
                'language'          => 'Tiếng Việt',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Nỗi Buồn Chiến Tranh',
                'slug'              => 'noi-buon-chien-tranh',
                'author'            => 'Bảo Ninh',
                'publisher'         => 'NXB Trẻ',
                'price'             => 90000,
                'description'       => 'Tác phẩm văn học chiến tranh xúc động, tái hiện nỗi đau và sự mất mát sau cuộc chiến.',
                'short_description' => 'Văn học chiến tranh đầy xúc động.',
                'stock'             => 8,
                'category_id'       => 1,
                'image'             => 'noi-buon-chien-tranh.jpg',
                'pages'             => 315,
                'language'          => 'Tiếng Việt',
            ],
            [
                'title'             => 'Sherlock Holmes - Toàn Tập (3 Tập)',
                'slug'              => 'sherlock-holmes-toan-tap-3-tap',
                'author'            => 'Arthur Conan Doyle',
                'publisher'         => 'NXB Văn Học',
                'price'             => 360000,
                'original_price'    => 420000,
                'description'       => 'Bộ truyện trinh thám kinh điển nhất mọi thời đại về thám tử tài ba Sherlock Holmes.',
                'short_description' => 'Truyện trinh thám kinh điển mọi thời đại.',
                'stock'             => 14,
                'category_id'       => 1,
                'image'             => 'sherlock-holmes-toan-tap-3-tap.jpg',
                'pages'             => 1200,
                'language'          => 'Tiếng Việt',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Thiền Cho Người Mới Bắt Đầu',
                'slug'              => 'thien-cho-nguoi-moi-bat-dau',
                'author'            => 'Ian Tuhovsky',
                'publisher'         => 'NXB Hồng Đức',
                'price'             => 79000,
                'description'       => 'Hướng dẫn thiền định cơ bản, giúp bạn tìm sự bình yên trong cuộc sống bận rộn.',
                'short_description' => 'Hướng dẫn thiền định cho người mới.',
                'stock'             => 20,
                'category_id'       => 2,
                'image'             => 'thien-cho-nguoi-moi-bat-dau.jpg',
                'pages'             => 190,
                'language'          => 'Tiếng Việt',
            ],
            [
                'title'             => 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh',
                'slug'              => 'toi-thay-hoa-vang-tren-co-xanh',
                'author'            => 'Nguyễn Nhật Ánh',
                'publisher'         => 'NXB Trẻ',
                'price'             => 85000,
                'original_price'    => 99000,
                'description'       => 'Tiểu thuyết thiếu niên nổi tiếng, kể câu chuyện tuổi thơ đẹp đẽ và xúc động ở miền quê Việt Nam.',
                'short_description' => 'Câu chuyện tuổi thơ đẹp đẽ ở miền quê.',
                'stock'             => 26,
                'category_id'       => 1,
                'image'             => 'toi-thay-hoa-vang-tren-co-xanh.jpg',
                'pages'             => 378,
                'language'          => 'Tiếng Việt',
                'is_featured'       => true,
            ],
            [
                'title'             => 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
                'slug'              => 'tuoi-tre-dang-gia-bao-nhieu',
                'author'            => 'Rosie Nguyễn',
                'publisher'         => 'NXB Nhã Nam',
                'price'             => 95000,
                'description'       => 'Sách phát triển bản thân dành cho giới trẻ, chia sẻ câu chuyện và bài học sống.',
                'short_description' => 'Sách truyền cảm hứng cho giới trẻ.',
                'stock'             => 30,
                'category_id'       => 2,
                'image'             => 'tuoi-tre-dang-gia-bao-nhieu.jpg',
                'pages'             => 285,
                'language'          => 'Tiếng Việt',
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
