services:
  - type: web
    name: booklovers
    env: docker
    plan: free
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
